### ISSUE TITLE
Error in bencodezen blog

### ISSUE THREAD

**Issue by rickfalck** [bencodezen/bencodezen#58]
Hi Ben, 

going to the blog page throws this error (inspecting in chrome). The error message continues to show if I move from page to page, but if I reload the page it goes away until I go to the blog page. That's an easy way to confirm the source of the error, and it makes sense it is the blog page as it is an error about tags.

vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "tags". Expected Array, got String with value "WorkflowWednesday".

found in

---> <BlogPostPreview> at src/.vuepress/components/BlogPostPreview.vue
       <BlogPostList> at src/.vuepress/components/BlogPostList.vue
         <V93285720> at src/blog/README.md
           <Content>
             <Page> at src/.vuepress/theme/layouts/Page.vue
               <Layout> at src/.vuepress/theme/Layout.vue
                 <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
                   <Root>
warn @ vue.runtime.esm.js?2b0e:619
assertProp @ vue.runtime.esm.js?2b0e:1705
validateProp @ vue.runtime.esm.js?2b0e:1632
loop @ vue.runtime.esm.js?2b0e:4659
initProps @ vue.runtime.esm.js?2b0e:4692
initState @ vue.runtime.esm.js?2b0e:4633
Vue._init @ vue.runtime.esm.js?2b0e:5000
VueComponent @ vue.runtime.esm.js?2b0e:5148
createComponentInstanceForVnode @ vue.runtime.esm.js?2b0e:3283
init @ vue.runtime.esm.js?2b0e:3114
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
updateChildren @ vue.runtime.esm.js?2b0e:6210
patchVnode @ vue.runtime.esm.js?2b0e:6313
updateChildren @ vue.runtime.esm.js?2b0e:6187
patchVnode @ vue.runtime.esm.js?2b0e:6313
updateChildren @ vue.runtime.esm.js?2b0e:6187
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
Vue.$forceUpdate @ vue.runtime.esm.js?2b0e:3963
forceRender @ vue.runtime.esm.js?2b0e:3641
(anonymous) @ vue.runtime.esm.js?2b0e:3663
(anonymous) @ vue.runtime.esm.js?2b0e:336
Promise.then (async)
resolveAsyncComponent @ vue.runtime.esm.js?2b0e:3686
createComponent @ vue.runtime.esm.js?2b0e:3200
_createElement @ vue.runtime.esm.js?2b0e:3416
createElement @ vue.runtime.esm.js?2b0e:3353
vm._c @ vue.runtime.esm.js?2b0e:3485
(anonymous) @ BlogPostList.vue?14d8:44
renderList @ vue.runtime.esm.js?2b0e:2630
render @ BlogPostList.vue?14d8:39
Vue._render @ vue.runtime.esm.js?2b0e:3542
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
updateChildren @ vue.runtime.esm.js?2b0e:6210
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
Vue.$forceUpdate @ vue.runtime.esm.js?2b0e:3963
forceRender @ vue.runtime.esm.js?2b0e:3641
(anonymous) @ vue.runtime.esm.js?2b0e:3663
(anonymous) @ vue.runtime.esm.js?2b0e:336
Promise.then (async)
resolveAsyncComponent @ vue.runtime.esm.js?2b0e:3686
createComponent @ vue.runtime.esm.js?2b0e:3200
_createElement @ vue.runtime.esm.js?2b0e:3416
createElement @ vue.runtime.esm.js?2b0e:3353
vm._c @ vue.runtime.esm.js?2b0e:3485
render @ README.md?b968:8
Vue._render @ vue.runtime.esm.js?2b0e:3542
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
patch @ vue.runtime.esm.js?2b0e:6510
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
(anonymous) @ vue-router.esm.js?8c4f:2748
(anonymous) @ vue-router.esm.js?8c4f:2747
updateRoute @ vue-router.esm.js?8c4f:2174
(anonymous) @ vue-router.esm.js?8c4f:2037
(anonymous) @ vue-router.esm.js?8c4f:2159
step @ vue-router.esm.js?8c4f:1843
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
(anonymous) @ vue-router.esm.js?8c4f:2154
step @ vue-router.esm.js?8c4f:1843
(anonymous) @ vue-router.esm.js?8c4f:1847
(anonymous) @ vue-router.esm.js?8c4f:2139
(anonymous) @ vue-router.esm.js?8c4f:1921
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
(anonymous) @ vue-router.esm.js?8c4f:1847
(anonymous) @ vue-router.esm.js?8c4f:2139
Promise.then (async)
beforeEnter @ routes.js?fc18:48
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
(anonymous) @ vue-router.esm.js?8c4f:1847
(anonymous) @ vue-router.esm.js?8c4f:2139
(anonymous) @ Layout.vue?3e79:142
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
(anonymous) @ vue-router.esm.js?8c4f:1847
(anonymous) @ vue-router.esm.js?8c4f:2139
(anonymous) @ redirect.js?605e:26
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
push @ vue-router.esm.js?8c4f:2365
push @ vue-router.esm.js?8c4f:2782
handler @ vue-router.esm.js?8c4f:1066
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911

**Comment by bencodezen** [comment]
Ahh I'm so sorry for missing this. My notifications became out of control over the years and clearly I dropped the ball on this. Thank you so much for reporting this. Hopefully it's fixed now!
