### ISSUE TITLE
Bad link on your "Learn" page

### ISSUE THREAD

**Issue by adriatic** [bencodezen/bencodezen#80]
![image](https://user-images.githubusercontent.com/2712405/99752814-16810980-2ab3-11eb-85f9-19b4c09c04a7.png)

... and I was so happy to see this guide (I read dozen and dozens of articles on how to create a VuePress Documentation Site and none of this is current 😢

**Comment by bencodezen** [comment]
Wow. I failed to see any of my issues back in 2020. So sorry for not responding to this for over a year. \

I'll be sure to keep a closer eye on the repo in the future. Thanks for filing the issue!
