### ISSUE TITLE
Hello from Centered/Cassidy

### ISSUE THREAD

**Issue by codemonkeysunite** [bencodezen/bencodezen#99]
Ben -

That was so gracious of you to mention us this week.  Cassidy showed me your video!

Thank you for your thoughtful analysis of what we do - and I would love to show you our user analytics to see if that does what you'd like...and also hear your thoughts on how you'd like it extended.

Reach me anytime at steven@centered.app.

- Steven

**Comment by bencodezen** [comment]
Thanks for reaching out @codemonkeysunite! Would love to chat more. I'll send you an email!
